import { Inter } from 'next/font/google';
import Header from '../components/Header';
import { useModalContext, ModalProvider } from '@/context/modalContext';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ModalProvider>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </ModalProvider>
        </html>
    );
}
